Journey.WebApp/Controllers/TravelerTripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Journey.WebApp.Data;

namespace Journey.WebApp.Controllers
{
    public class TravelerTripsController : Controller
    {
        private readonly JourneyDBContext _context;

        public TravelerTripsController(JourneyDBContext context)
        {
            _context = context;
        }

        // GET: TravelersTrips
        public async Task<IActionResult> Index()
        {
            var travelerID = (int)TempData.Peek("TravelerID");
            var journeyDBContext = _context.TravelersTrips.Where(tc => tc.Traveler.Id == travelerID)
                                                          .Include(t => t.Trip)
                                                          .ThenInclude(tr => tr.TripCities)
                                                          .ThenInclude(tc => tc.City);
            return View(await journeyDBContext.ToListAsync());
        }

        // GET: TravelersTrips/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TravelersTrips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TravelersTrips travelersTrips, Trip trip)
        {
            if (ModelState.IsValid)
            {
                trip.DateCreated = DateTime.Now;
                _context.Add(trip);
                await _context.SaveChangesAsync();

                var travelerID = (int)TempData.Peek("TravelerID");
                travelersTrips.TravelerId = travelerID;
                travelersTrips.TripId = trip.Id;

                _context.Add(travelersTrips);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(travelersTrips);
        }

        // GET: TravelersTrips/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelerID = (int)TempData.Peek("TravelerID");

            var travelersTrips = await _context.TravelersTrips.Where(tc => tc.Traveler.Id == travelerID)
                                                              .Include(t => t.Trip)
                                                              .FirstOrDefaultAsync(tt => tt.TripId == id);
            if (travelersTrips == null)
            {
                return NotFound();
            }
            return View(travelersTrips);
        }

        // POST: TravelersTrips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, TravelersTrips tt)
        {
            
            
            if (id != tt.TripId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var travelerTrip = tt.Trip;
                try
                {
                    travelerTrip.Id = id;
                    _context.Update(travelerTrip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelersTripsExists(travelerTrip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(id);
        }

        // GET: TravelersTrips/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelersTrips = await _context.TravelersTrips
                .Include(t => t.Traveler)
                .Include(t => t.Trip)
                .FirstOrDefaultAsync(m => m.TripId == id);
            if (travelersTrips == null)
            {
                return NotFound();
            }

            return View(travelersTrips);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var travelersTrips = await _context.TravelersTrips
                                               .Include(t => t.Traveler)
                                               .Include(t => t.Trip)
                                               .FirstOrDefaultAsync(m => m.TripId == id); 

            _context.TravelersTrips.Remove(travelersTrips);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelersTripsExists(long id)
        {
            return _context.TravelersTrips.Any(e => e.TripId == id);
        }
    }
}

Journey.WebApp/Controllers/TripCitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Journey.WebApp.Data;
using Journey.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Journey.WebApp.Controllers
{
    [Authorize]
    public class TripCitiesController : Controller
    {
        private readonly JourneyDBContext _context;

        public TripCitiesController(JourneyDBContext context)
        {
            _context = context;
        }

        public IActionResult Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCity = new TripCities();

            tripCity.TripId = (long)id;
            return View("Edit", tripCity);
        }


        // GET: TravelersTrips/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCities = await _context.TripCities.Include(tc => tc.City).FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripCities == null)
            {
                return NotFound();
            }
            return View(tripCities);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TripCities tripCities, City city)
        {
            if (ModelState.IsValid)
            {
                var cityID = await MyUtility.CityFindOrAdd(_context, city);
                tripCities.CityId = cityID;

                if (tripCities.Id == 0)
                {
                    _context.Add(tripCities);
                }
                else
                {
                    _context.Update(tripCities);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "TravelerTrips", null);
            }
            return View(tripCities);
        }


        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCity = await _context.TripCities.Include(tc => tc.Trip)
                                                    .ThenInclude(t => t.TripCities)
                                                    .Include(tc => tc.City)
                                                    .Include(tc => tc.TripDetails)
                                                    .ThenInclude(td => td.TripActivities)
                                                    .FirstOrDefaultAsync(tc => tc.Id == id);


            if (tripCity == null)
            {
                return NotFound();
            }
            ViewBag.trip = tripCity.Trip.TripName;
            ViewBag.city = tripCity.City.CityName;
            ViewBag.current = tripCity.Id;

            var tripCityIds = tripCity.Trip.TripCities.OrderBy(tc => tc.StartDate).Select(tc => tc.Id).ToArray();
            var index = Array.IndexOf(tripCityIds, id);

            var indexNext = tripCityIds[index + 1 >= tripCityIds.Length ? 0 : index + 1];
            var indexPrev = tripCityIds[index - 1 < 0 ? tripCityIds.Length - 1 : index - 1];

            var nextCity = await _context.TripCities.Include(tc => tc.City)
                                                    .FirstOrDefaultAsync(tc => tc.Id == indexNext);
            var prevCity = await _context.TripCities.Include(tc => tc.City)
                                                    .FirstOrDefaultAsync(tc => tc.Id == indexPrev);

            ViewBag.next = indexNext;
            ViewBag.previous = indexPrev;
            ViewBag.nextCity = nextCity.City.CityName;
            ViewBag.prevCity = prevCity.City.CityName;

            return View(tripCity.TripDetails);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCities = await _context.TripCities.Include(tc => tc.City)
                                                      .Include(t => t.Trip)
                                                      .FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripCities == null)
            {
                return NotFound();
            }

            return View(tripCities);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tripCities = await _context.TripCities.Include(tc => tc.City)
                                           .Include(t => t.Trip)
                                           .FirstOrDefaultAsync(tc => tc.Id == id);

            _context.TripCities.Remove(tripCities);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "TravelerTrips", null);
        }
    }
}

Journey.WebApp/Views/TravelerTrips/Create.cshtml
@model Journey.WebApp.Data.TravelersTrips

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>TravelersTrips</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Trip.TripName" class="control-label"></label>
                <input asp-for="Trip.TripName" class="form-control" />
                <span asp-validation-for="Trip.TripName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.StartDate" class="control-label"></label>
                <input asp-for="Trip.StartDate" class="form-control" />
                <span asp-validation-for="Trip.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.EndDate" class="control-label"></label>
                <input asp-for="Trip.EndDate" class="form-control" />
                <span asp-validation-for="Trip.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.Descript" class="control-label"></label>
                <input asp-for="Trip.Descript" class="form-control" />
                <span asp-validation-for="Trip.Descript" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Journey.WebApp/Views/TravelerTrips/Delete.cshtml
@model Journey.WebApp.Data.TravelersTrips

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TravelersTrips</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Traveler)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Traveler.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Trip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Trip.TripName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TripId" />
        <input type="hidden" asp-for="TravelerId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Journey.WebApp/Views/TravelerTrips/Edit.cshtml
@model Journey.WebApp.Data.TravelersTrips

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>TravelersTrips</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TripId" />
            <input type="hidden" asp-for="TravelerId" />
            <input type="hidden" asp-for="Trip.DateCreated" />
            <div class="form-group">
                <label asp-for="Trip.TripName" class="control-label"></label>
                <input asp-for="Trip.TripName" class="form-control" />
                <span asp-validation-for="Trip.TripName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.StartDate" class="control-label"></label>
                <input asp-for="Trip.StartDate" class="form-control" />
                <span asp-validation-for="Trip.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.EndDate" class="control-label"></label>
                <input asp-for="Trip.EndDate" class="form-control" />
                <span asp-validation-for="Trip.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trip.Descript" class="control-label"></label>
                <input asp-for="Trip.Descript" class="form-control" />
                <span asp-validation-for="Trip.Descript" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Journey.WebApp/Views/TravelerTrips/Index.cshtml
@model IEnumerable<Journey.WebApp.Data.TravelersTrips>

@{
    ViewData["Title"] = "Places";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string accordion;
}

<h2>Trips</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table id="trips" class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Trip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trip.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trip.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            accordion = $"#accordion{item.TripId}";
            <tr data-toggle="collapse" data-target="@accordion" class="clickable">
                <td>
                    @Html.ActionLink(item.Trip.TripName, "Edit", new { id = item.TripId })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trip.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trip.EndDate)
                </td>
                <td>
                    <a data-toggle="collapse" data-target="@accordion" class="clickable">Details</a> |
                    @Html.ActionLink("Delete", "Delete", new { id = item.TripId })
                </td>
            </tr>

            <tr id="@accordion.Substring(1, accordion.Length - 1)" class="collapse">
                <td colspan="4">
                    <div>
                        <table class="table table-condensed table-hover">
                            <tbody>

                                @foreach (var tr in item.Trip.TripCities)
                                {
                                    <tr>
                                        <td width="$(trips).children('tr:first').children('tr:first').width()">
                                            @Html.ActionLink(tr.City.CityName, "Edit", "TripCities", new { id = tr.Id })
                                        </td>
                                        <td>
                                            @tr.StartDate.ToString("dd-MMM-yy") 
                                        </td>
                                        <td>
                                            @tr.EndDate.ToString("dd-MMM-yy")
                                        </td>
                                        <td>
                                            @Html.ActionLink("Details", "Details", "TripCities", new { id = tr.Id }) | 
                                            @Html.ActionLink("Delete", "Delete", "TripCities", new { id = tr.Id })
                                        </td>
                                    </tr>
                                }

                                <tr>
                                    <td colspan="4">
                                        @Html.ActionLink("Add City", "Create", "TripCities",  new { id = item.TripId })
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>