Journey.WebApp/Controllers/TravelerTripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Journey.WebApp.Data;

namespace Journey.WebApp.Controllers
{
    public class TravelerTripsController : Controller
    {
        private readonly JourneyDBContext _context;

        public TravelerTripsController(JourneyDBContext context)
        {
            _context = context;
        }

        // GET: TravelersTrips
        public async Task<IActionResult> Index()
        {
            var travelerID = (int)TempData.Peek("TravelerID");
            var journeyDBContext = _context.TravelersTrips.Where(tc => tc.Traveler.Id == travelerID)
                                                          .Include(t => t.Trip)
                                                          .ThenInclude(tr => tr.TripCities)
                                                          .ThenInclude(tc => tc.City);
            return View(await journeyDBContext.ToListAsync());
        }

        // GET: TravelersTrips/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TravelersTrips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TravelersTrips travelersTrips, Trip trip)
        {
            if (ModelState.IsValid)
            {
                trip.DateCreated = DateTime.Now;
                _context.Add(trip);
                await _context.SaveChangesAsync();

                var travelerID = (int)TempData.Peek("TravelerID");
                travelersTrips.TravelerId = travelerID;
                travelersTrips.TripId = trip.Id;

                _context.Add(travelersTrips);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(travelersTrips);
        }

        // GET: TravelersTrips/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelerID = (int)TempData.Peek("TravelerID");

            var travelersTrips = await _context.TravelersTrips.Where(tc => tc.Traveler.Id == travelerID)
                                                              .Include(t => t.Trip)
                                                              .FirstOrDefaultAsync(tt => tt.TripId == id);
            if (travelersTrips == null)
            {
                return NotFound();
            }
            return View(travelersTrips);
        }

        // POST: TravelersTrips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, TravelersTrips tt)
        {
            
            
            if (id != tt.TripId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var travelerTrip = tt.Trip;
                try
                {
                    travelerTrip.Id = id;
                    _context.Update(travelerTrip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelersTripsExists(travelerTrip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(id);
        }

        // GET: TravelersTrips/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelersTrips = await _context.TravelersTrips
                .Include(t => t.Traveler)
                .Include(t => t.Trip)
                .FirstOrDefaultAsync(m => m.TripId == id);
            if (travelersTrips == null)
            {
                return NotFound();
            }

            return View(travelersTrips);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var travelersTrips = await _context.TravelersTrips
                                               .Include(t => t.Traveler)
                                               .Include(t => t.Trip)
                                               .FirstOrDefaultAsync(m => m.TripId == id); 

            _context.TravelersTrips.Remove(travelersTrips);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelersTripsExists(long id)
        {
            return _context.TravelersTrips.Any(e => e.TripId == id);
        }
    }
}

Journey.WebApp/Controllers/TripActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Journey.WebApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Journey.WebApp.Controllers
{
    public class TripActivitiesController : Controller
    {
        private readonly JourneyDBContext _context;

        public TripActivitiesController(JourneyDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripActivities = new TripActivities();

            tripActivities.TripDetailsId = (long)id;

            var td = await _context.TripDetails.FindAsync(id);
            ViewBag.tripCityId = td.TripCitiesId;

            return View("Edit", tripActivities);
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripActivities = await _context.TripActivities.Include(ta => ta.TripDetails)
                                               .FirstOrDefaultAsync(ta => ta.Id == id);

            if (tripActivities == null)
            {
                return NotFound();
            }

            ViewBag.tripCityId = tripActivities.TripDetails.TripCitiesId;

            return View(tripActivities);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TripActivities tripActivities)
        {
            if (ModelState.IsValid)
            {
                if (tripActivities.Id == 0)
                {
                    _context.Add(tripActivities);
                }
                else
                {
                    _context.Update(tripActivities);
                }
                await _context.SaveChangesAsync();
                var td = await _context.TripDetails.FindAsync(tripActivities.TripDetailsId);
                return RedirectToAction("Details", "TripCities", new { id = td.TripCitiesId });
            }
            return View(tripActivities);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripActivities = await _context.TripActivities.FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripActivities == null)
            {
                return NotFound();
            }

            //ViewBag.city = tripActivities.TripCities.City.CityName;

            return View(tripActivities);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tripActivities = await _context.TripActivities.Include(ta => ta.TripDetails)
                                               .FirstOrDefaultAsync(tc => tc.Id == id);

            _context.TripActivities.Remove(tripActivities);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "TripCities", new { id = tripActivities.TripDetails.TripCitiesId });
        }

    }
}

Journey.WebApp/Controllers/TripCitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Journey.WebApp.Data;
using Journey.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Journey.WebApp.Controllers
{
    [Authorize]
    public class TripCitiesController : Controller
    {
        private readonly JourneyDBContext _context;

        public TripCitiesController(JourneyDBContext context)
        {
            _context = context;
        }

        public IActionResult Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCity = new TripCities();

            tripCity.TripId = (long)id;
            return View("Edit", tripCity);
        }


        // GET: TravelersTrips/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCities = await _context.TripCities.Include(tc => tc.City).FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripCities == null)
            {
                return NotFound();
            }
            return View(tripCities);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TripCities tripCities, City city)
        {
            if (ModelState.IsValid)
            {
                var cityID = await MyUtility.CityFindOrAdd(_context, city);
                tripCities.CityId = cityID;

                if (tripCities.Id == 0)
                {
                    _context.Add(tripCities);
                }
                else
                {
                    _context.Update(tripCities);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "TravelerTrips", null);
            }
            return View(tripCities);
        }


        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCity = await _context.TripCities.Include(tc => tc.Trip)
                                                    .ThenInclude(t => t.TripCities)
                                                    .Include(tc => tc.City)
                                                    .Include(tc => tc.TripDetails)
                                                    .ThenInclude(td => td.TripActivities)
                                                    .FirstOrDefaultAsync(tc => tc.Id == id);


            if (tripCity == null)
            {
                return NotFound();
            }
            ViewBag.trip = tripCity.Trip.TripName;
            ViewBag.city = tripCity.City.CityName;
            ViewBag.current = tripCity.Id;

            var tripCityIds = tripCity.Trip.TripCities.OrderBy(tc => tc.StartDate).Select(tc => tc.Id).ToArray();
            var index = Array.IndexOf(tripCityIds, id);

            var indexNext = tripCityIds[index + 1 >= tripCityIds.Length ? 0 : index + 1];
            var indexPrev = tripCityIds[index - 1 < 0 ? tripCityIds.Length - 1 : index - 1];

            var nextCity = await _context.TripCities.Include(tc => tc.City)
                                                    .FirstOrDefaultAsync(tc => tc.Id == indexNext);
            var prevCity = await _context.TripCities.Include(tc => tc.City)
                                                    .FirstOrDefaultAsync(tc => tc.Id == indexPrev);

            ViewBag.next = indexNext;
            ViewBag.previous = indexPrev;
            ViewBag.nextCity = nextCity.City.CityName;
            ViewBag.prevCity = prevCity.City.CityName;

            return View(tripCity.TripDetails);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripCities = await _context.TripCities.Include(tc => tc.City)
                                                      .Include(t => t.Trip)
                                                      .FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripCities == null)
            {
                return NotFound();
            }

            return View(tripCities);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tripCities = await _context.TripCities.Include(tc => tc.City)
                                           .Include(t => t.Trip)
                                           .FirstOrDefaultAsync(tc => tc.Id == id);

            _context.TripCities.Remove(tripCities);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "TravelerTrips", null);
        }
    }
}

Journey.WebApp/Controllers/TripDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Journey.WebApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Journey.WebApp.Controllers
{
    public class TripDetailsController : Controller
    {
        private readonly JourneyDBContext _context;

        public TripDetailsController(JourneyDBContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripDetails = new TripDetails();

            tripDetails.TripCitiesId = (long)id;

            var city = await _context.TripCities.Include(tc => tc.City)
                                         .FirstOrDefaultAsync(tc => tc.Id == id);

            ViewBag.city = city.City.CityName;

            return View("Edit", tripDetails);
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripDetails = await _context.TripDetails.Include(td => td.TripCities)
                                            .ThenInclude(tc => tc.City)
                                            .FirstOrDefaultAsync(td => td.Id == id);

            if (tripDetails == null)
            {
                return NotFound();
            }

            ViewBag.city = tripDetails.TripCities.City.CityName;

            return View(tripDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TripDetails tripDetails)
        {
            if (ModelState.IsValid)
            {
                if (tripDetails.Id == 0)
                {
                    _context.Add(tripDetails);
                }
                else
                {
                    _context.Update(tripDetails);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "TripCities", new { id = tripDetails.TripCitiesId });
            }
            return View(tripDetails);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripDetails = await _context.TripDetails.Include(td => td.TripCities)
                                                        .ThenInclude(tc => tc.City)
                                                        .FirstOrDefaultAsync(tc => tc.Id == id);

            if (tripDetails == null)
            {
                return NotFound();
            }

            ViewBag.city = tripDetails.TripCities.City.CityName;

            return View(tripDetails);
        }

        // POST: TravelersTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tripDetails = await _context.TripDetails.Include(td => td.TripCities)
                                                        .ThenInclude(tc => tc.City)
                                                        .FirstOrDefaultAsync(tc => tc.Id == id);

            _context.TripDetails.Remove(tripDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "TripCities", new { id = tripDetails.TripCitiesId });
        }
    }
}

Journey.WebApp/Views/TripCities/Delete.cshtml
@model Journey.WebApp.Data.TripCities

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TripCities</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Trip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Trip.TripName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City.CityName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index" asp-controller="TravelerTrips">Back to List</a>
    </form>
</div>

Journey.WebApp/Views/TripCities/Details.cshtml
@model IEnumerable<Journey.WebApp.Data.TripDetails>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<h3>@ViewBag.trip</h3>
<h4><a asp-action="Details" asp-route-id="@ViewBag.previous"> @ViewBag.prevCity</a> >> <b>@ViewBag.city</b> >> <a asp-action="Details" asp-route-id="@ViewBag.next">@ViewBag.nextCity</a></h4>



    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Accomodation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.InboundTransportation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OutboundTransportation)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accomodation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InboundTransportation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OutboundTransportation)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="TripDetails" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Delete" asp-controller="TripDetails" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AccomodationDetails)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InboundTransportationDetails)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OutboundTransportationDetails)
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().Activity)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().ActivityDate)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().ActivityType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().Cost)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().Currency)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TripActivities.FirstOrDefault().Note)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var a in item.TripActivities)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.Activity)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.ActivityDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.ActivityType)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.Cost)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.Currency)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => a.Note)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-controller="TripActivities" asp-route-id="@a.Id">Edit</a> |
                                            <a asp-action="Delete" asp-controller="TripActivities" asp-route-id="@a.Id">Delete</a>
                                        </td>
                                    </tr>
                                }
                                <tr>
                                    <td colspan="7">
                                        <a asp-action="Create" asp-controller="TripActivities" asp-route-id="@item.Id">Add Activity</a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a asp-action="Create" asp-controller="TripDetails" asp-route-id="@ViewBag.current">Add Trip Details</a>
    </p>



    <div>
        <a asp-action="Index" asp-controller="TravelerTrips">Back to List</a>
    </div>

Journey.WebApp/Views/TripCities/Edit.cshtml
@model Journey.WebApp.Data.TripCities

@{
    ViewData["Title"] = "City";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>City</h2>

<h4>TripCities</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
            <input type="hidden" asp-for="TripId" />
            @await Html.PartialAsync("_City", @Model.City)
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="TravelerTrips">Back to List</a>
    @if (Model.Id != 0)
    {
        @Html.Raw(" | ")
        @Html.ActionLink("Details", "Details", new { id = Model.Id })
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}